/* eslint-disable react/no-unescaped-entities */
import { Star } from "@mui/icons-material";
import SchoolIcon from "@mui/icons-material/School";
import ShoppingCartIcon from "@mui/icons-material/ShoppingCart";
import {
  Box,
  Button,
  Card,
  IconButton,
  Typography,
  useMediaQuery,
} from "@mui/material";
import Head from "next/head";
import Image from "next/image";
import {
  SiGithub,
  SiInstagram,
  SiLinkedin,
  SiTiktok,
  SiYoutube,
} from "react-icons/si";
import { text } from "stream/consumers";

export default function Home() {
  const desktop = useMediaQuery("(min-width:900px)");
  return (
    <Box>
      <Head>
        <title>Gardini Dev</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icone.png" />
        <style>
          @import
          url('https://fonts.googleapis.com/css2?family=Domine&family=Heebo&family=Kalnia&family=Poppins:wght@400;600;700&display=swap');
        </style>
      </Head>
      <main>
        <Box
          sx={{
            display: "flex",
            justifyContent: "center",
            alignItems: "center",
            height: "100vh",
          }}
        >
          <Box
            // className="vidro"
            sx={{
              // background: "#0979d483",
              // backgroundColor: "rgba(9, 121, 212, 0.5)",
              // boxShadow: "0 8px 32px 0 #0a0549",
              // backdropFilter: "blur(10px)", // Adiciona o desfoque ao fundo
              // borderTop: "2px solid white",
              mt: desktop ? 35 : 0,
              width: desktop ? "50vw" : "100vw",
              height: "100vh",
              borderTopLeftRadius: desktop ? 60 : 0,
              borderTopRightRadius: desktop ? 60 : 0,
              overflow: "visible",
              color: "#ffffff",
              // color: "#26314d",
            }}
          >
            <Box
              sx={{
                backdropFilter: "none",
                display: "flex",
                flexDirection: "column",
                justifyContent: "center",
                alignItems: "center",
                position: "relative",
                paddingTop: desktop ? 5 : 0,
              }}
            >
              <Image
                src="/foto3.png"
                alt="foto"
                width={440}
                height={495}
                style={{
                  borderTopLeftRadius: desktop ? 10 : 0,
                  borderTopRightRadius: desktop ? 10 : 0,
                }}
                className="fade-image"
              ></Image>
              <Box
                sx={{
                  position: "relative",
                  top: -80,
                  display: "flex",
                  justifyContent: "center",
                  textAlign: "center",
                  flexDirection: "column",
                }}
              >
                <Typography
                  variant={"h3"}
                  fontFamily={"Poppins"}
                  sx={{
                    color: "#ffffff",
                    fontWeight: "bold",
                    fontSize: 32,
                    // textShadow: "2px 2px 4px rgba(0, 0, 0, 5)",
                  }}
                >
                  Gardini Dev
                </Typography>
                <Box sx={{widht:"100%", marginY:1}}>
                  <Typography
                    variant={"subtitle1"}
                    fontFamily={"Poppins"}
                    textAlign={"center"}
                    // marginTop={1}
                    // marginBottom={1}
                    // marginLeft={2}
                    // marginRight={2}
                  >
                    Aprenda frontend e consiga sua<br></br> primeira vaga de emprego!
                  </Typography>
                </Box>
                <Box
                  sx={{
                    display: "flex",
                    justifyContent: "space-around",
                    width: "100%",
                  }}
                >
                  <IconButton
                    href="https://www.tiktok.com/@gardini.dev"
                    target="_blank"
                    sx={{
                      color: "#ffffff",
                      // my: 2,
                      // fontSize: 20,
                    }}
                  >
                    <SiTiktok fontSize={"30px"} />
                  </IconButton>
                  <IconButton
                    href="https://www.instagram.com/gardinidev/"
                    target="_blank"
                    sx={{
                      color: "#ffffff",
                      // my: 2,
                      // fontSize: 20,
                    }}
                  >
                    <SiInstagram fontSize={"30px"} />
                  </IconButton>
                  <IconButton
                    href="https://www.youtube.com/@Gardinidev"
                    target="_blank"
                    sx={{
                      color: "#ffffff",
                      // my: 2,
                      // fontSize: 20,
                    }}
                  >
                    <SiYoutube fontSize={"30px"} />
                  </IconButton>
                  <IconButton
                    href="https://www.linkedin.com/in/gabrielgardini/"
                    target="_blank"
                    sx={{
                      color: "#ffffff",
                      // my: 2,
                      // fontSize: 20,
                    }}
                  >
                    <SiLinkedin fontSize={"30px"} />
                  </IconButton>
                </Box>
              </Box>
              <Button
                href="https://go.hotmart.com/D97410048K"
                target="_blank"
                className="ghost-animation-button"
                variant="contained"
                sx={{
                  top: -50,
                  width: "75%",
                  backgroundColor: "#ffffff",
                  color: "#5a1096",
                  fontFamily: "Poppins",
                  fontWeight: "bold",
                  my: 2,
                  fontSize: 20,
                  textTransform: "none",
                }}
                startIcon={<SchoolIcon />}
              >
                consiga sua vaga!
              </Button>
              <Button
                variant="contained"
                href="mailto:gardinidev@gmail.com"

                target="_blank"
                sx={{
                  top: -50,

                  width: "75%",
                  backgroundColor: "#ffffff",
                  color: "#5a1096",
                  fontFamily: "Poppins",
                  my: 2,
                  // mb: 10,
                  fontSize: 20,
                  textTransform: "none",
                }}
                startIcon={<Star />}
              >
                Parcerias aqui!
              </Button>
              <Button
                variant="contained"
                href="https://shpe.site/gardinidev"
                target="_blank"
                sx={{
                  top: -50,

                  width: "75%",
                  backgroundColor: "#ffffff",
                  color: "#5a1096",
                  fontFamily: "Poppins",
                  my: 2,
                  // mb: 10,
                  fontSize: 20,
                  textTransform: "none",
                }}
                startIcon={<ShoppingCartIcon />}
              >
                Melhore seu setup!
              </Button>
              <Button
                variant="contained"
                href="https://github.com/GabrielGardini"
                target="_blank"
                sx={{
                  top: -50,

                  width: "75%",
                  backgroundColor: "#ffffff",
                  color: "#5a1096",
                  fontFamily: "Poppins",
                  mt: 2,
                  mb: 10,
                  fontSize: 20,
                  textTransform: "none",
                }}
                startIcon={<SiGithub />}
              >
                Acesse meu Github
              </Button>
            </Box>
          </Box>
        </Box>
      </main>
    </Box>
  );
}
