/* eslint-disable react/no-unescaped-entities */
import SchoolIcon from "@mui/icons-material/School";
import ShoppingCartIcon from "@mui/icons-material/ShoppingCart";
import {
  Box,
  Button,
  Card,
  IconButton,
  Typography,
  useMediaQuery,
} from "@mui/material";
import Head from "next/head";
import Image from "next/image";
import {
  SiGithub,
  SiInstagram,
  SiLinkedin,
  SiTiktok,
  SiYoutube,
} from "react-icons/si";

export default function Home() {
  const desktop = useMediaQuery("(min-width:900px)");
  return (
    <Box>
      <Head>
        <title>Gardini Dev</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icone.png" />
        <style>
          @import
          url('https://fonts.googleapis.com/css2?family=Domine&family=Heebo&family=Kalnia&family=Poppins:wght@400;600;700&display=swap');
        </style>
      </Head>
      <main>
        <Box
          sx={{
            display: "flex",
            justifyContent: "center",
            alignItems: "center",
            height: "100vh",
          }}
        >
          <Card
            // className="vidro"
            sx={{
              // background: "#0979d483",
              backgroundColor: "rgba(9, 121, 212, 0.5)", // Fundo semi-transparente
              boxShadow: "0 8px 32px 0 #0a0549",
              // backdropFilter: "blur(10px)", // Adiciona o desfoque ao fundo
              borderTop: "2px solid white",
              mt: 35,
              width: desktop ? "40vw" : "100vw",
              height: "100vh",
              borderTopLeftRadius: 60,
              borderTopRightRadius: 60,
              overflow: "visible",
              color: "white",
            }}
          >
            <Box
              sx={{
                backdropFilter: "none",
                display: "flex",
                flexDirection: "column",
                justifyContent: "center",
                alignItems: "center",
                position: "relative",
                paddingTop: 20,
              }}
            >
              <Image
                src="/foto3.png"
                alt="foto"
                width={235}
                height={250}
                style={{
                  borderRadius: "50%",
                  border: "2px solid white",
                  position: "absolute",
                  top: -130,
                }}
              ></Image>
              <Typography
                variant={"h3"}
                fontFamily={"Poppins"}
                sx={{
                  color: "#ffffff",
                  textShadow: "2px 2px 4px rgba(0, 0, 0, 5)",
                }}
              >
                Gardini Dev
              </Typography>

              <Typography
                variant={"subtitle1"}
                fontFamily={"Poppins"}
                textAlign={"center"}
                marginTop={2}
                marginBottom={2}
              >
                Aprenda Frontend todos os dias aqui!
              </Typography>
              <Box
                sx={{
                  display: "flex",
                  justifyContent: "space-between",
                  width: "60%",
                }}
              >
                <IconButton
                  href="https://www.tiktok.com/@gardini.dev"
                  target="_blank"
                  sx={{
                    color: "white",
                    // my: 2,
                    // fontSize: 20,
                  }}
                >
                  <SiTiktok fontSize={"30px"} />
                </IconButton>
                <IconButton
                  href="https://www.instagram.com/gardinidev/"
                  target="_blank"
                  sx={{
                    color: "white",
                    // my: 2,
                    // fontSize: 20,
                  }}
                >
                  <SiInstagram fontSize={"30px"} />
                </IconButton>
                <IconButton
                  href="https://www.youtube.com/@Gardinidev"
                  target="_blank"
                  sx={{
                    color: "white",
                    // my: 2,
                    // fontSize: 20,
                  }}
                >
                  <SiYoutube fontSize={"30px"} />
                </IconButton>
                <IconButton
                  href="https://www.linkedin.com/in/gabrielgardini/"
                  target="_blank"
                  sx={{
                    color: "white",
                    // my: 2,
                    // fontSize: 20,
                  }}
                >
                  <SiLinkedin fontSize={"30px"} />
                </IconButton>
              </Box>
              <Button
                href="https://go.hotmart.com/D93924915H"
                target="_blank"
                className="ghost-animation-button"
                variant="contained"
                sx={{
                  width: "75%",
                  // backgroundColor: "#FF8C00",
                  color: "white",
                  fontFamily: "Poppins",
                  my: 2,
                  fontSize: 20,
                  textTransform: "none",
                }}
                startIcon={<SchoolIcon />}
              >
                Aprenda Aqui!
              </Button>
              <Button
                variant="contained"
                href="https://shpe.site/gardinidev"
                target="_blank"
                sx={{
                  width: "75%",
                  backgroundColor: "#FF0000 ",
                  color: "white",
                  fontFamily: "Poppins",
                  my: 2,
                  // mb: 10,
                  fontSize: 20,
                  textTransform: "none",
                }}
                startIcon={<ShoppingCartIcon />}
              >
                Melhore seu setup!
              </Button>
              <Button
                variant="contained"
                href="https://github.com/GabrielGardini"
                target="_blank"
                sx={{
                  width: "75%",
                  backgroundColor: "black ",
                  color: "white",
                  fontFamily: "Poppins",
                  mt: 2,
                  mb: 10,
                  fontSize: 20,
                  textTransform: "none",
                }}
                startIcon={<SiGithub />}
              >
                Acesse meu Github
              </Button>
            </Box>
          </Card>
        </Box>
      </main>
    </Box>
  );
}
